version: "3.3"
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment:
      - API_URL
    networks:
      - internalapp
      - default

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - JWT_SECRET
      - DB_HOST
    networks:
      - internalapp

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - internalapp

networks:
  internalapp:
    internal: true