version: "3.3"
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80"
    environment:
      - API_URL
      - BASIC_ENABLED
      - BASIC_USER
      - BASIC_PASSWORD
    networks:
      - internalapp
      - default

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    expose:
      - 3001
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - JWT_SECRET
      - DB_HOST
      - SIGNED_FLAG_SECRET
      - PRODUCTION
      - SMTP_EMAIL
      - SMTP_PASSWORD
      - SMTP_DOMAIN
      - DOMAIN
    networks:
      - internalapp
      - default

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - internalapp

networks:
  internalapp:
    internal: true