version: "3.3"
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - internalapp
      - default

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - internalapp

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - "./bdd/:/docker-entrypoint-initdb.d/"
    networks:
      - internalapp

networks:
  internalapp:
    internal: true